main: me.z3ndovo.CasinoPlus.Core
version: 1.0
name: CasinoPlus
description: This plugin does so much stuff it can't be contained!
author: z3ndovo
api-version: 1.13
depend: [Vault]

commands:
  createslots:
    usage: /<command>
    description: Run commands
  test:
    usage: /<command>

permissions:
  casinoplus.*:
    description: Use all CasinoPlus commands.
    children:
      casinoplus.admin: true
      casinoplus.slots.use.all: true
    default: op
  casinoplus.admin:
    description: Use admin commands.
    default: op
  casinoplus.slots.use.all:
    description: Use all slot machines.
    default: true